os: linux
dist: bionic
language: c
compiler: gcc

before_script:
  - pip3 install meson

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - python3
      - python3-pip
      - python3-setuptools
      - ninja-build
      - libdrm-dev
      - libcairo2-dev
      - libpixman-1-dev
      - libsystemd-dev
      - libexif-dev
      - libjpeg-turbo8-dev
      - libpng-dev
      - libtiff-dev
      - libgif-dev
      - libudev-dev
      - libinput-dev
      - libxkbcommon-dev
      - libglib2.0-dev
      - libpoppler-glib-dev
      - libmotif-dev
      - libxpm-dev
      - libxt-dev
      - libxext-dev
      - libx11-dev

script:
  - mkdir build-travis
  - meson build-travis
  - ninja -C build-travis
