.TH FBGS 1 "(c) 1999\-2012 Gerd Hoffmann" "FBGS 2.09" "PostScript/pdf viewer for the linux framebuffer console"
\#
\#
.SH NAME
fbgs \- Poor man's PostScript/pdf viewer for the linux framebuffer console.
\#
\#
.SH SYNOPSIS
\fBfbgs\fP\
 [\fB\-l\fP|\fB\-xl\fP|\fB\-xxl\fP|\fB\-r\fP \fIn\fP]\
 [\fB\-c\fP]\
 [\fB\-b\fP]\
 [\fB\-p\fP\ \fIpassword\fP]\
 [\fB\--fp\fP\ \fInumber\fP]\
 [\fB\--lp\fP\ \fInumber\fP]\
 [\fIfbi\ options\fP]\
 \fIfile\fP
\#
\#
.SH DESCRIPTION
.BR Fbgs
is a simple wrapper script which takes a \fIPostScript\fP (PS) or \fIPortable
Document Format\fP (PDF) file as input, renders the pages using
.BR gs (1) 
\- GhostScript \- into a temporary directory and finally calls
.BR fbi (1)
to display them.
.SH OPTIONS
.BR Fbgs
understands all
.BR fbi (1)
options (they are passed through), except: store, list, text, (no)comments, e,
(no)edit, (no)backup, (no)preserve, (no)readahead, cachemem, blend.
.P
Additionally you can specify:
.TP
.B -h, --help
Print usage info (overwrites fbi option).
.TP
.B -b, --bell
Emit a beep when the document is ready.
.TP
.B -c, --color
To render the pages in color (default is N&B).
.TP
.B -l
To get the pages rendered with 100 dpi (default is 75).
.TP
.B -xl
To get the pages rendered with 120 dpi.
.TP
.B -xxl
To get the pages rendered with 150 dpi.
.TP
.BI "-r" "\ n" ", --resolution" "\ n"
To get the pages rendered with \fIn\fP dpi (overwrites fbi option).
.TP
.BI "-fp" "\ number" ", --firstpage" "\ number"
Begins interpreting on the designated page of the document.
.TP
.BI "-lp" "\ number" ", --lastpage" "\ number"
Stops interpreting after the designated page of the document.
.TP
.BI "-p" "\ password" ", --password" "\ password"
You can use this option if your PDF file requires a \fIpassword\fP.
\#
\#
.SH "SEE ALSO"
.BR fbi (1),
.BR gs (1)
\#
\#
.SH AUTHOR
Gerd Hoffmann
.BR <gerd@kraxel.org>
\#
\#
.SH COPYRIGHT
Copyright (c) 1999-2012 Gerd Hoffmann <gerd@kraxel.org>
.P
This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.
.P
This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.
.P
You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 675 Mass Ave,
Cambridge, MA 02139, USA.
