.TH FBGS 1 "(c) 1999\-2003 Gerd Knorr" "FBGS 2.07" "PostScript/pdf viewer for the linux framebuffer console"
\#
\#
.SH NAME
fbgs \- Poor man's PostScript/pdf viewer for the linux framebuffer console.
\#
\#
.SH SYNOPSIS
\fBfbgs\fP\ [\fB\-l\fP|\fB\-xl\fP|\fB\-xxl\fP]\ [\fB\-c\fP]\ [\fB\-p\fP\ \fIpassword\fP]\ [\fIfbi\ options\fP]\ \fIfile\fP
\#
\#
.SH DESCRIPTION
.BR Fbgs
is a simple wrapper script which takes a \fIPostScript\fP (PS) or
\fIPortable Document Format\fP (PDF) file as input, renders the pages
using
.BR gs (1) 
\- GhostScript \- into a temporary directory and finally calls
.BR fbi (1)
to display them.
.SH OPTIONS
.BR Fbgs
understands all
.BR fbi (1)
options (they are passed through).
Additionally you can specify:
.TP
\fB\-l\fP
To get the pages rendered with 100 dpi (default is 75).
.TP
\fB\-xl\fP
To get the pages rendered with 120 dpi.
.TP
\fB\-xxl\fP
To get the pages rendered with 150 dpi.
.TP
\fB\-c\fP
To render the pages in color (default is N&B).
.TP
\fB\-p\fP \fIpassword\fP
You can use on if your PDF file requires password.
\#
\#
.SH AUTHOR
Gerd Knorr
.BR <kraxel@bytesex.org>
\#
\#
.SH SEE ALSO
.BR fbi (1),
.BR gs (1)
